### ISSUE TITLE
Problem with predict function

### ISSUE THREAD

**Issue by AlexScheu** [jamesepaterson/markrecaptureworkshop#1]
Line 183: of the marrecaptureworkshop code

This doesn't work:
reals <- predict(dipper.cjs.models[[2]], 
                 newdata = newdipper, 
                 se = TRUE)

Thats what R gives me:
Error in `contrasts<-`(`*tmp*`, value = contr.funs[1 + isOF[nn]]) : 
  Contrasts can be applied to factors with 2 or more steps only

**Comment by AlexScheu** [comment]
This is how the data frame newdipper is created:
newdipper <- data.frame(sex = c("Female", "Male"))
Creating it this way gives the wrong format. 

This works:
newdipper <- dipper[c(1,23),]

**Comment by jamesepaterson** [comment]
I can't replicate your error, and am (still) getting estimates with my original version. The "newdata" should just need rows with the levels of the grouping variables (as a factor). The error indicates the function is not finding a factor with at least two levels (e.g. "Female", "Male") . You can check with str(dipper) and str(newdipper). 

Can you share a reproducible example?

**Comment by AlexScheu** [comment]
Dear James Peterson,

Thanks for the super fast answer, and kudos to your well-commented code: a great help!


When I use

newdipper <- data.frame(sex = c("Female", "Male"))

I get this:

 newdipper
     sex
1 Female
2   Male

Which gives me the error.


When I use

newdipper <- dipper[c(1,23),]


I get this:

> newdipper
        ch    sex
1  0000001 Female
23 0000001   Male

Which does not give me the error, and which also works fine fo the ggplot command.

Thanks for your comment,

Alex

-------------------------------------------------------
Dr. Alexander Scheuerlein

Bunzlauer Strasse 12
13125 Berlin - Karow

Phone: 	+49 (0) 151 12318896

***@***.***
***@***.***
-------------------------------------------------------

**Comment by jamesepaterson** [comment]
The predict function just uses the "sex" column from newdipper (which defines groups, not "ch"), so the two objects (newdipper) are essentially the same. If the same factor levels exist in dipper$sex and newdipper$sex, then the predict function should not return that error.

For example, this also works:

`reals <- predict(dipper.cjs.models[[2]],
                  newdata = data.frame(sex = dipper[c(1,23),2]), 
                 se = TRUE)`

Anyways, glad you got a version working for you, but I can't find any error with the current version. Thanks!

**Comment by AlexScheu** [comment]
Here's the difference:

> str(newdipper)
'data.frame':	2 obs. of  1 variable:
 $ sex: Factor w/ 2 levels "Female","Male": 1 2
> newdipper = data.frame(sex = c("Female", "Male"))
> str(newdipper)
'data.frame':	2 obs. of  1 variable:
 $ sex: chr  "Female" „Male“

Doesn’t work


> newdipper = data.frame(sex = dipper[c(1,23),2])
> str(newdipper)
'data.frame':	2 obs. of  1 variable:
 $ sex: Factor w/ 2 levels "Female","Male": 1 2

Works

newdipper = data.frame(sex = as.factor(c("Female", "Male“)))

Also works.



Thanks for your patience,

Alex


 
-------------------------------------------------------
Dr. Alexander Scheuerlein

Bunzlauer Strasse 12
13125 Berlin - Karow

Phone: 	+49 (0) 151 12318896

***@***.***
***@***.***
-------------------------------------------------------

**Comment by jamesepaterson** [comment]
Hi Alex,
The default argument for data.frame() is that stringsAsFactors = TRUE). I suspect it is likely that you have changed this to FALSE (e.g. "options(stringsAsFactors = FALSE)").

Thus, in your R session, str(newdipper) returns that "sex" is a character string, and in my session, str(newdipper) returns that "sex" is a factor. Although my code works with the default settings, I will update to be explicit in the call to data.frame() to avoid this confusion.

`newdipper = data.frame(sex = as.factor(c("Female", "Male“)))`
`str(newdipper)`
'data.frame':	2 obs. of  1 variable:
 $ sex: Factor w/ 2 levels "Female","Male": 1 2
`newdipper = data.frame(sex = c("Female", "Male"), stringsAsFactors = TRUE)`
`str(newdipper)`
'data.frame':	2 obs. of  1 variable:
 $ sex: Factor w/ 2 levels "Female","Male": 1 2

James

**Comment by AlexScheu** [comment]
Hi James,

This makes a lot of sense, thanks a lot.

Alex
-------------------------------------------------------
Dr. Alexander Scheuerlein

Bunzlauer Strasse 12
13125 Berlin - Karow

Phone: 	+49 (0) 151 12318896

***@***.***
***@***.***
-------------------------------------------------------
